### ISSUE TITLE
Support for docblock annotations

### ISSUE THREAD

**Issue by sandermarechal** [claytonrcarter/tree-sitter-phpdoc#28]
Is it possible to add support for docblock annotations? For example:

```
<?php

use Symfony\Component\Routing\Annotation\Route;

class FooController
{
    /**
     * @Route("foo")
     */
    public function foo()
    {
    }
}
```

So, anything starting with @ that is followed by an imported or fully qualified classname should be highlighed. And parameters passed to that annotation as well, much like the standard PHP 8 attributes highlight.

Is that possible?

**Comment by claytonrcarter** [comment]
> So, anything starting with @ that is followed by an imported or fully qualified classname
> 
This usage is entirely new to me. I’d like to keep support focused on documented syntax (standard php doc) And commonly used extensions (phpstan/psalm/etc). 

Can you tell me more about this usage, or point me to any documentation, tooling or more examples?

As I recall, it’s hard (maybe not possible?) to limit tags (eg ***@***.***`) only to dynamic types that have been imported (eg `use Route`).

**Comment by sandermarechal** [comment]
This usage is called "PHP annotations" and is extremely common though it is slowly being phased out in new projects since PHP 8 has attributes now. Some examples:

* Doctrine: https://www.doctrine-project.org/projects/doctrine-orm/en/2.17/reference/annotations-reference.html
* Symfony:
** Routing: https://symfony.com/doc/5.3/routing.html
** Security, Templating, ParamConvertes: https://symfony.com/bundles/SensioFrameworkExtraBundle/current/index.html
** Rest APIs: https://fosrestbundle.readthedocs.io/en/3.x/param_fetcher_listener.html
** API documentation: https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#using-the-bundle
** Seralization: https://symfony.com/doc/5.3/components/serializer.html#attributes-groups and https://jmsyst.com/libs/serializer/master/reference/annotations
* Laminas (formelry Zend Framework): https://docs.laminas.dev/laminas-form/v3/form-creation/attributes-or-annotations/

There are many, many more. Almost all these depend on https://packagist.org/packages/doctrine/annotations as a generic annotations parser. As you can see on that page, over 2000 other packages depend (directly) on this one.

**Comment by sandermarechal** [comment]
The simple solution may be to simply highlight anything that has the format of `@SomeString` or `@SomeString()` (matching brackets). The Doctrine annotations parser will throw an exception for any `@` tag that is not a known phpdoc/psalm/phpstan/phpunit tag and not a valid classname.

**Comment by claytonrcarter** [comment]
Gotcha. Thank you for the info and context. I don’t plan on implementing support for this myself, but I would merge a suitable PR that does.

**Comment by claytonrcarter** [comment]
> I don’t plan on implementing support for this myself, but I would merge a suitable PR that does.

Closing for now, but this statement is still true! 😄
