### ISSUE TITLE
`tree-sitter-phpdoc` is not published to package registries (npm, crates.io, etc)

### ISSUE THREAD

**Issue by raulchedrese** [claytonrcarter/tree-sitter-phpdoc#33]
👋

I'm looking to use this package in a Rust project but it doesn't look to be listed on crates.io https://crates.io/search?q=tree-sitter-phpdoc.

Is this intentional?

**Comment by claytonrcarter** [comment]
> Is this intentional?

Yes and no. I have no issue w/ publishing a crate, except that I don't have time/capacity to set it up and manage it. (I'll also note that we have an NPM package that is laughably out of date at this point.) I think that most consumers of the package are doing so by referencing the git repo directly. In fact, I just did that last week for a Rust project consuming [tree-sitter-ledger](https://github.com/cbarrete/tree-sitter-ledger), which also isn't on crates.io. It was pretty easy; the docs are at https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

I don't plan to change anything here at this time, but if it's a major blocker and/or you'd like continue the discussion, please reopen this issue. Thanks for asking!

**Comment by raulchedrese** [comment]
Thanks for the info! I think I should be able to get a away with just referencing the git repo directly.
