### ISSUE TITLE
@var description is not parsed if no variable name is used

### ISSUE THREAD

**Issue by mikehaertl** [claytonrcarter/tree-sitter-phpdoc#6]
If `@var` is not followed by a variable name (like in a property declaration in a class) the description is not parsed as `@text` but as comment:

![ts_var_string](https://user-images.githubusercontent.com/675062/150111213-52125145-9e68-4e13-88f2-17cf6789f0bc.png)

This gets especially weird if the description contains linebreaks:

![ts_phpdoc_linebreak](https://user-images.githubusercontent.com/675062/150111303-4d4fbc4c-6c71-4ec8-bdf2-029721c1ecb1.png)

**Comment by claytonrcarter** [comment]
Yes, this makes sense for the moment. `@var` requires a variable name, so leaving it out means tree-sitter will not recognize that tag and generate a parse error. The [phpDoc docs for `@var`](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/var.html#var) state

> The @var tag MUST contain the name of the element it documents. An exception to this is when a declaration only refers to a single property or constant. In that case, the name of the property or constant MAY be omitted.

And I have implemented this for the former, not the latter. `psalm` and `phpstan` also encourage/allow the element name to be omitted, and I have some local changes that support that, but they're not pushed yet.

**Comment by claytonrcarter** [comment]
I believe that this is now fixed in f54431c. Thanks!

**Comment by mikehaertl** [comment]
Confirmed. Thanks for the quick fix.
